[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bolt"
version = "0.0.1"
dependencies = [
    'importlib-metadata; python_version>="3.8"',
]

[project.scripts]
bolt = "bolt:bolt"
